// Auto-generated YouTube video metadata for schema markup
// Source: YouTube Data API v3

export const youtubeVideos = {
  '3vEQKShP_Tg': {
    title: 'Laser Cataract Surgery with Dr. Tokuhara',
    description: 'What is it like to have laser cataract surgery?  Are you anxious about having cataract surgery?  Dr. Tokuhara\'s patient,',
    duration: 'PT3M49S',
    thumbnailUrl: 'https://i.ytimg.com/vi/3vEQKShP_Tg/maxresdefault.jpg',
    uploadDate: '2021-07-26',
  },
  '4EEq6cg9zyY': {
    title: 'Vivity Lens:  Cataract Surgery Behind The Scenes With Dr. Tokuhara',
    description: 'In this video, Dr. Tokuhara invites you into the operating room in Palm Springs on the very first day with the new Vivit',
    duration: 'PT4M23S',
    thumbnailUrl: 'https://i.ytimg.com/vi/4EEq6cg9zyY/hqdefault.jpg',
    uploadDate: '2020-10-27',
  },
  '7VkbQx36LeI': {
    title: '‘Botched’ Cataract Surgery Edition:  Posterior Capsule Rupture Explained',
    description: '“Why can’t I see after cataract surgery?”  “I already had cataract surgery, why do I need to have surgery again.”  Dr. T',
    duration: 'PT7M24S',
    thumbnailUrl: 'https://i.ytimg.com/vi/7VkbQx36LeI/maxresdefault.jpg',
    uploadDate: '2021-04-27',
  },
  '7mkouTcQWOo': {
    title: 'Cataract Recovery:  What happens after surgery in the recovery room?',
    description: 'After cataract surgery, you\'re brought to the recovery unit.  In this video, Dr. Tokuhara talks to the surgery nurses ab',
    duration: 'PT3M46S',
    thumbnailUrl: 'https://i.ytimg.com/vi/7mkouTcQWOo/maxresdefault.jpg',
    uploadDate: '2023-03-12',
  },
  '85V5DGG6Rw0': {
    title: 'Clareon Lens:  Cataract Surgery with Dr. Tokuhara',
    description: 'First Clareon Lens Cataract Surgery in Coachella Valley.  Join Dr. Tokuhara in the operating room for a hands on look at',
    duration: 'PT4M55S',
    thumbnailUrl: 'https://i.ytimg.com/vi/85V5DGG6Rw0/maxresdefault.jpg',
    uploadDate: '2021-09-21',
  },
  'B8sM9Xa5mus': {
    title: '\'Botched\' Cataract Surgery Edition:  Iris Damage Repair',
    description: '"Why do I have glare after cataract surgery?  Why is my pupil not round?  Why did my eye change color after cataract sur',
    duration: 'PT8M15S',
    thumbnailUrl: 'https://i.ytimg.com/vi/B8sM9Xa5mus/maxresdefault.jpg',
    uploadDate: '2021-01-03',
  },
  'F8Z81PMgVR0': {
    title: 'How do we do cataract surgery in 2023?',
    description: 'In this lecture, Dr. Tokuhara discusses cataract surgery tools and technology that we use in 2023.  This is a cataract s',
    duration: 'PT1H6M56S',
    thumbnailUrl: 'https://i.ytimg.com/vi/F8Z81PMgVR0/hqdefault.jpg',
    uploadDate: '2023-06-20',
  },
  'JzspGX4RErQ': {
    title: 'Yag Laser Capsulotomy for Posterior Capsule Opacification',
    description: 'Blurred vision and glare after cataract surgery?  It may be easily reversed with laser.    In this video, Dr. Tokuhara d',
    duration: 'PT4M44S',
    thumbnailUrl: 'https://i.ytimg.com/vi/JzspGX4RErQ/hqdefault.jpg',
    uploadDate: '2023-05-03',
  },
  'NJ1dx9nKHCA': {
    title: 'What to do when you get dust in your eyes?',
    description: 'The Coachella Valley is one of the driest, windiest places in the world.  What should you do when the wind blows sand an',
    duration: 'PT1M44S',
    thumbnailUrl: 'https://i.ytimg.com/vi/NJ1dx9nKHCA/maxresdefault.jpg',
    uploadDate: '2024-05-17',
  },
  'XeELWvMkBY8': {
    title: 'What Happens in Cataract Pre-Op?',
    description: 'Welcome to the Pre-Op Area at Desert Vision Center! 👁️✨ Join Dr. Tokuhara as he takes you behind the scenes of the pre-o',
    duration: 'PT4M27S',
    thumbnailUrl: 'https://i.ytimg.com/vi/XeELWvMkBY8/maxresdefault.jpg',
    uploadDate: '2025-04-03',
  },
  'Yomf55PktXU': {
    title: 'What\'s the Difference Between PanOptix and PanOptix Pro? Real Patient Experience with Dr. Tokuhara',
    description: 'Thinking about cataract surgery in 2025? Wondering whether to choose the PanOptix Pro lens over the original PanOptix?',
    duration: 'PT2M43S',
    thumbnailUrl: 'https://i.ytimg.com/vi/Yomf55PktXU/maxresdefault.jpg',
    uploadDate: '2025-06-20',
  },
  'YxmR_NSv5-k': {
    title: '5 Questions to Ask Before Cataract Surgery',
    description: '"What questions should I ask my Cataract Surgeon?"  Do you or someone you love have cataracts?  Before you have cataract',
    duration: 'PT3M56S',
    thumbnailUrl: 'https://i.ytimg.com/vi/YxmR_NSv5-k/maxresdefault.jpg',
    uploadDate: '2021-07-18',
  },
  'ZoV2RTUlEZo': {
    title: 'Welcome to Desert Vision Center:  Dr. Tokuhara Cataract Surgeon',
    description: 'From the talented team at Desert Vision Center, we bring you videos of our daily life, our patients, and our world-class',
    duration: 'PT55S',
    thumbnailUrl: 'https://i.ytimg.com/vi/ZoV2RTUlEZo/maxresdefault.jpg',
    uploadDate: '2022-02-12',
  },
  'ZrnRIEa0F44': {
    title: 'Fixing a Dislocated Lens Implant:  Yamane Technique',
    description: 'Does cataract surgery last forever? What happens when the lens implant from cataract surgery dislocates?  Dr. Tokuhara d',
    duration: 'PT3M36S',
    thumbnailUrl: 'https://i.ytimg.com/vi/ZrnRIEa0F44/maxresdefault.jpg',
    uploadDate: '2022-01-03',
  },
  'aXl4PhNQBg8': {
    title: 'Dr. Tokuhara Recognized on NBC as the Best Cataract Surgeon in Coachella Valley',
    description: 'In this short segment clip from NBC’s Roggin Report (aired May 16, 2025), Dr. Tokuhara is recognized as the best catarac',
    duration: 'PT24S',
    thumbnailUrl: 'https://i.ytimg.com/vi/aXl4PhNQBg8/maxresdefault.jpg',
    uploadDate: '2025-05-21',
  },
  'i7ME2ufk1iM': {
    title: 'First PanOptix Pro Cataract Surgery in Coachella Valley: Dr. Tokuhara',
    description: 'Watch the first PanOptix Pro lens implant in the Coachella Valley, performed by Dr. Keith Tokuhara, a Fellowship trained',
    duration: 'PT5M11S',
    thumbnailUrl: 'https://i.ytimg.com/vi/i7ME2ufk1iM/maxresdefault.jpg',
    uploadDate: '2025-06-10',
  },
  'iYKugpBcnQY': {
    title: 'What are Cataracts?  Dr. Tokuhara Explains',
    description: 'What are cataracts?  What are the symptoms of cataracts?  How do you know if you have cataracts?  In this video, Dr. Tok',
    duration: 'PT4M13S',
    thumbnailUrl: 'https://i.ytimg.com/vi/iYKugpBcnQY/maxresdefault.jpg',
    uploadDate: '2021-02-28',
  },
  'im9_7hi4Dqg': {
    title: 'My Cataract Drops:  Phone App by Dr. Tokuhara ',
    description: 'If you’ve been told you have cataracts, you probably have questions... and not enough clear answers.  The My Cataract Dr',
    duration: 'PT37S',
    thumbnailUrl: 'https://i.ytimg.com/vi/im9_7hi4Dqg/maxresdefault.jpg',
    uploadDate: '2026-05-05',
  },
  'm3xHlebhPUQ': {
    title: 'Dr. Tokuhara Patient Testimonial:  Eric Redd’s Cataract Experience',
    description: 'What is it like to have cataract surgery?  Listen to Golf Professional, Eric Redd, talk about his personal experience.',
    duration: 'PT2M29S',
    thumbnailUrl: 'https://i.ytimg.com/vi/m3xHlebhPUQ/maxresdefault.jpg',
    uploadDate: '2020-07-18',
  },
  'oPV_lteXtzo': {
    title: 'The unspoken story of cataract referral kickbacks:   What you need to know',
    description: 'I get this question often enough from patients that I thought it would be worthwhile to make a video about it. It’s the',
    duration: 'PT4M51S',
    thumbnailUrl: 'https://i.ytimg.com/vi/oPV_lteXtzo/maxresdefault.jpg',
    uploadDate: '2024-07-02',
  },
  'pm6T4CUmLrE': {
    title: 'Philip Ferranti’s Cataract Journey:  Coachella Valley Hiking Expert',
    description: 'What is it like to have cataract surgery?  Hiking expert and renowned author, Philip Ferranti, shares his journey throug',
    duration: 'PT5M47S',
    thumbnailUrl: 'https://i.ytimg.com/vi/pm6T4CUmLrE/maxresdefault.jpg',
    uploadDate: '2023-02-26',
  },
  'sG3rN3WXW3o': {
    title: 'Ethical Cataract Surgery & Patient-First Eye Care | Dr. Tokuhara at Ethics in Eyecare 2025',
    description: 'On June 28, 2025, local physicians and advocates gathered for the Ethics in Eyecare event hosted by Desert Vision Center',
    duration: 'PT1M22S',
    thumbnailUrl: 'https://i.ytimg.com/vi/sG3rN3WXW3o/maxresdefault.jpg',
    uploadDate: '2025-06-29',
  },
  'uCbLzD-KXe4': {
    title: 'Cataracts and Toric Lens Implants for Patients with Astigmatism',
    description: 'The astigmatism lens implant used in cataract surgery is called a toric lens.  In this video, Dr. Tokuhara reviews astig',
    duration: 'PT8M28S',
    thumbnailUrl: 'https://i.ytimg.com/vi/uCbLzD-KXe4/maxresdefault.jpg',
    uploadDate: '2020-06-29',
  },
  'vdD3lBubt58': {
    title: 'Cataract Surgery in a Monocular Eye | Mr. Baird’s Journey to Desert Vision Center',
    description: 'Mr. Baird only has vision in one eye, making him a monocular patient - and deciding to undergo cataract surgery was not',
    duration: 'PT7M33S',
    thumbnailUrl: 'https://i.ytimg.com/vi/vdD3lBubt58/maxresdefault.jpg',
    uploadDate: '2025-03-21',
  },
};
